# Generated by Django 4.2.7 on 2025-12-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='platform_status',
            field=models.CharField(choices=[('Review', 'Review'), ('Disabled', 'Disabled'), ('Rejected', 'Rejected'), ('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_course_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Disabled', 'Disabled'), ('Published', 'Published')], default='Published', max_length=100),
        ),
    ]
