# Generated by Django 4.2.7 on 2026-01-13 10:20

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_course_platform_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=10, prefix=''),
        ),
    ]
