# Generated by Django 4.2.7 on 2026-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cartorderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='teachers',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='api.teacher'),
        ),
    ]
