# Generated by Django 4.2.7 on 2026-01-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cartorder_teachers_cartorder_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='coupons',
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.coupon'),
        ),
    ]
