# Generated by Django 4.2.7 on 2026-02-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_cartorderitem_coupons_cartorderitem_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Order', 'New Order'), ('New Review', 'New Review'), ('New Course Question', 'New Course Question'), ('Draft', 'Draft'), ('Course Published', 'Course Published'), ('Course Enrollment Completed', 'Course Enrollment Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course-file'),
        ),
    ]
